### ISSUE TITLE
Tradução das Diretrizes de Contribuição

### ISSUE THREAD

**Issue by dgv** [golangbr/golangbr.org#9]
http://golang.org/doc/contribute.html

**Comment by carlisia** [comment]
Essa pagina estah feita: https://github.com/golangbr/golangbr.org/blob/35a4a9c1d493931d326f11ed401f116fed203510/pt_BR/doc/contribua.html

Falta deploy.

c/c @marcosinger

**Comment by carlisia** [comment]
Eu notei uma certa confusao em relacao a nome dos arquivos.

No site do Go, a pagina https://golang.org/project/ estah em um arquivo chamado [contrib.html](https://github.com/golang/go/blob/90ffb7c806c049ececeb2c6ce7fa0dbb056ae4ca/doc/contrib.html).

No site do Go BR, a pagina http://www.golangbr.org/projeto/ estah em um arquivo chamado [contribua.html](https://github.com/golangbr/golangbr.org/blob/master/pt_BR/doc/contribua.html)

Uma questao eh que alem da pagina `contrib.html` o site do Go tambem tem a pagina `contribute.html`, que eh a pagina em questao nesse ticket. Essa eh a pagina que precisa chamar `contribua.html`.

De qualquer forma, vou consertar. A pagina do projecto estah apontando para uma versao ingles das directrizes de contribuicao. Mas agora que tem a versao em portugues, vou consertar esse link e deletar o arquivo que estah em ingles.
